const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
const GET_MOVIESACTIONS_RECEIVED = 'GET_MOVIESACTIONS_RECEIVED';
const GET_MOVIES_RECEIVED = 'GET_MOVIES_RECEIVED';
const GET_MOVIES_ACTIONS = 'GET_MOVIES_ACTIONS';

export{
    GET_MOVIES_LIST,
    GET_MOVIESACTIONS_RECEIVED,
    GET_MOVIES_ACTIONS,
    GET_MOVIES_RECEIVED
}